component_depth: 1
languages:
- java
exclude:
- ./contrib/.*
- ./contrib/bin/.*
- ./contrib/bin/org/.*
- ./contrib/bin/org/apache/.*
- ./contrib/bin/org/apache/tools/.*
- ./contrib/bin/org/apache/tools/ant/.*
- ./contrib/bin/org/apache/tools/ant/taskdefs/.*
- ./contrib/bin/org/apache/tools/ant/taskdefs/optional/.*
- ./contrib/charts/.*
- ./contrib/charts/xml/.*
- ./contrib/charts/xsl/.*
- ./contrib/fonts/.*
- ./contrib/fonts/gladiator/.*
- ./contrib/fonts/gladiator/svg/.*
- ./contrib/jsvg/.*
- ./contrib/lib/.*
- ./contrib/rasterizertask/.*
- ./contrib/scroll/.*
- ./contrib/tiledTranscoder/.*
- ./lib/.*
- ./lib/build/.*
- ./samples/.*
- ./samples/extensions/.*
- ./samples/extensions/xsl/.*
- ./samples/lib/.*
- ./samples/solitaire/.*
- ./samples/solitaire/cards/.*
- ./samples/solitaire/script/.*
- ./samples/tests/.*
- ./samples/tests/spec/.*
- ./samples/tests/spec/color/.*
- ./samples/tests/spec/coordinates/.*
- ./samples/tests/spec/filters/.*
- ./samples/tests/spec/fonts/.*
- ./samples/tests/spec/interactivity/.*
- ./samples/tests/spec/linking/.*
- ./samples/tests/spec/masking/.*
- ./samples/tests/spec/painting/.*
- ./samples/tests/spec/paints/.*
- ./samples/tests/spec/rendering/.*
- ./samples/tests/spec/scripting/.*
- ./samples/tests/spec/scripting/textcontent/.*
- ./samples/tests/spec/shapes/.*
- ./samples/tests/spec/structure/.*
- ./samples/tests/spec/styling/.*
- ./samples/tests/spec/text/.*
- ./samples/tests/spec12/.*
- ./samples/tests/spec12/filters/.*
- ./samples/tests/spec12/paints/.*
- ./samples/tests/spec12/structure/.*
- ./samples/tests/spec12/structure/opera/.*
- ./samples/tests/spec12/structure/opera/multires/.*
- ./samples/tests/spec12/text/.*
